### ISSUE TITLE
About evaluating seed quality

### ISSUE THREAD

**Issue by lianxxx** [yaoqi-zd/SGAN#2]
Thank you for your repo.
I have a couple of questions about procedures of evaluating seed quality. 1. Do you evaluate seed quality on the train set or the train_aug set ? (I am confused you mentioned in eval_mIou.py that "DO NOT USE SEGMENTATIONCLASSAUG dir for evaluation, ... ")  2. How do you deal with the conflicting regions (which are given ignore labels eg. 255) when you evaluate seeds?

Thank you very much.

**Comment by lianxxx** [comment]
> Thank you for your repo.
> I have a couple of questions about procedures of evaluating seed quality. 1. Do you evaluate seed quality on the train set or the train_aug set ? (I am confused you mentioned in eval_mIou.py that "DO NOT USE SEGMENTATIONCLASSAUG dir for evaluation, ... ") 2. How do you deal with the conflicting regions (which are given ignore labels eg. 255) when you evaluate seeds?
> 
> Thank you very much.

**Comment by lianxxx** [comment]
Do you set the confusion region as 21? is that the reason you set number of classes as 22 which includes the ignore label.

**Comment by yaoqi-zd** [comment]
> Do you set the confusion region as 21? is that the reason you set number of classes as 22 which includes the ignore label.

eval_mIoU.py can evaluate the seed quality as well as segmentation results.
for seed quality: we evaluate seeds on train_aug split, ignore region is set to 21, the number of classes should be set to 22 so that ignore region can also be considered as a fake class and we wish such class occupies as small region as possible;
for segmentation results: we evaluate segmentation results on val or test split, the number of classes should be set to 21 since segmentation results contain no ignore regions.

**Comment by lianxxx** [comment]
Very clear now. Thank you for your reply.
