### ISSUE TITLE
Is seed_stage2.txt lost?

### ISSUE THREAD

**Issue by ucmmesa** [yaoqi-zd/SGAN#7]
When doing retrain step under dsrg sub-directory,a list file of seed_stage2.txt is needed.Is this file the same as seed_sdnet_seedseg.txt or lost?

**Comment by yaoqi-zd** [comment]
@ucmmesa hi, actually retrain brings little performance improvement for our method. If you want to try retrain step, you can refer [DSRG](https://github.com/speedinghzl/DSRG) or just the original deeplab-v2 repo. because in retrain step, we simply use cross entropy loss only for training.

btw, during training and testing of dsrg, you may get mIoU improvement by enlarge the input image size reasonably
